<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sketch-tool_Drop files here_selected</name>
   <tag></tag>
   <elementGuidId>89f6ce9b-690f-435a-aee7-0a9ad69d8470</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//sketch-tool[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>sketch-tool.selected</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>sketch-tool</value>
      <webElementGuid>6f70a6cb-43a0-4753-ab3e-1b826ce138fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tool</name>
      <type>Main</type>
      <value>pencil</value>
      <webElementGuid>f2d20d89-b2ed-49d3-aa5b-c31c91ea4106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tool-group</name>
      <type>Main</type>
      <value>brush</value>
      <webElementGuid>09d09f4d-c3dc-45c4-9ff9-061faa45470a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-linked-as</name>
      <type>Main</type>
      <value>tool</value>
      <webElementGuid>e1307189-0591-472d-b15b-36ece729b90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>pencil</value>
      <webElementGuid>0c2db352-5e9a-4276-a050-090917c9837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selected</value>
      <webElementGuid>e9d90310-e0b9-4c2b-aa88-fc7e3a397a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sketch-api&quot;]/sketchpad[@class=&quot;no-animate&quot;]/sketch-toolbar[1]/sketch-toolgroup[@class=&quot;top&quot;]/sketch-tool[@class=&quot;selected&quot;]</value>
      <webElementGuid>3c43ca8b-73bb-4f5f-9f21-f4931c9ca4d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sketch-tool[3]</value>
      <webElementGuid>c74dda0b-5584-4033-8227-795d98ddbc32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
