<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sketch-input-content_2px (1)</name>
   <tag></tag>
   <elementGuidId>d6c8940d-361d-4747-864f-f13562433b9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Line Width'])[1]/following::sketch-input-content[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>sketch-input.value0.sketch-input > sketch-input-content</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>sketch-input-content</value>
      <webElementGuid>c9e5c744-3d65-47d9-9c40-338d87b7aa23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>contenteditable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>af2e6b52-7b27-4277-8b68-5fbb313df9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e056a2d8-8ee3-499e-9115-ded600c02d30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>decimal</value>
      <webElementGuid>8d4db651-4cf6-4778-b195-13dd240c87c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2px</value>
      <webElementGuid>e2851551-b00b-4d11-b650-e37bec2b6103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;sketch-api&quot;]/sketch-popout[@class=&quot;sketch-style-popout&quot;]/sketch-popout-content[1]/sketch-toolconfig[1]/sketch-label[@class=&quot;sketch-RangeModule sketch-horizontal&quot;]/sketch-input-container[1]/sketch-input[@class=&quot;value0 sketch-input&quot;]/sketch-input-content[1]</value>
      <webElementGuid>9b2c9d67-037a-41cf-bece-16561ff03c24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Line Width'])[1]/following::sketch-input-content[1]</value>
      <webElementGuid>85d222ac-1830-4ef3-bf61-94a1686209d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outline'])[1]/following::sketch-input-content[2]</value>
      <webElementGuid>e9b7726a-1472-489f-bd02-930d6d76fb49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2px']/parent::*</value>
      <webElementGuid>c05102aa-1636-4054-bd87-e6f11c1b2190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sketch-input-container/sketch-input/sketch-input-content</value>
      <webElementGuid>3a12e2d9-1080-490f-8dd5-a43b915e46a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//sketch-input-content[(text() = '2px' or . = '2px')]</value>
      <webElementGuid>cc2d5c78-515e-40da-bfd1-fbe0f6c43c26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
